### ISSUE TITLE
Code release date?

### ISSUE THREAD

**Issue by kelvin34501** [zc-alexfan/arctic#1]

**Comment by zc-alexfan** [comment]
trying to release it within this week. but we will have to see.

**Comment by kelvin34501** [comment]
Thank you for your kind reply!

**Comment by zc-alexfan** [comment]
Update: 


Took longer than expected. Currently computing checksums for our files (#2)

**Comment by zc-alexfan** [comment]
It is released! Let me know if any problem comes up. Have fun!
