### ISSUE TITLE
fuse arctic and grab datasets?

### ISSUE THREAD

**Issue by noahcao** [zc-alexfan/arctic#11]
Hi, 

I noticed another dataset [GRAB](https://grab.is.tue.mpg.de/) having similar configurations as ARCTIC (without images). I wonder if you have tried to merge the two datasets or not. If I would like to train a 3D-only grasp/motion model, I think I can fuse the two datasets together? Do you think if there is any obstacle preventing this?

**Comment by zc-alexfan** [comment]
Hi, you cannot redistribute the two datasets. It is under our license.

**Comment by noahcao** [comment]
Oh, I am not trying to redistribute the two datasets. I meant to use them together, that's all (essentially, I am writing a data loader to combine the two datasets during training)... To do this and realize potential data distribution differences, I wondered if there are any setting differences for the datasets.

**Comment by zc-alexfan** [comment]
Closing stale issue. Please reopen for further discussion.
