### ISSUE TITLE
Hand mesh mismatch with the manopth

### ISSUE THREAD

**Issue by Eric-Gty** [zc-alexfan/arctic#15]
Hi Alex,

I just tried to use the differentiable manolayer here: https://github.com/hassony2/manopth/blob/master/manopth/manolayer.py, to reproduce the hand mesh with the provided beta and theta parameters. For some hand samples, the smplx and the manopth align with each other, but for some, it seems like the result doesn't really match, as below.
![Screenshot from 2023-06-15 01-27-47](https://github.com/zc-alexfan/arctic/assets/67919006/4d557c95-9c56-4909-9c38-fd046bce9b99)

Do you have any guess on the cause for this, or have you tried to use their manolayer before? Since the GT is axis-angle, so I don't think it's because of the wrong parameters of the manolayer

**Comment by zc-alexfan** [comment]
I have not used the hasson version before. 

Does it only happens for the left hand? Or right hand as well? Might not be related, but I recall smplx left hand shapedirs have some issues [here](https://github.com/facebookresearch/InterHand2.6M/blob/67ba1b8e2c8da0f79ba8a3de5bb401714b4ebea2/tool/MANO_render/render.py#L74).

**Comment by Eric-Gty** [comment]
> I have not used the hasson version before.
> 
> Does it only happen for the left hand? Or right hand as well? Might not be related, but I recall smplx left hand shapedirs have some issues [here](https://github.com/facebookresearch/InterHand2.6M/blob/67ba1b8e2c8da0f79ba8a3de5bb401714b4ebea2/tool/MANO_render/render.py#L74).

based on my observation, it may happen on the right hand. My guess for this is the different usage order of the global rotation and the translation for different implementations of manolayer. 

Btw, another quick question on the subsampled object mesh vertex here: https://github.com/zc-alexfan/arctic/blob/ccb88af2f21633f9f7227816b84d5d0f3764659a/common/object_tensors.py#L279. I think for the given GT, we only have the face information for the original mesh as here: https://github.com/zc-alexfan/arctic/blob/ccb88af2f21633f9f7227816b84d5d0f3764659a/common/object_tensors.py#LL281C1-L281C1. I would like to know how to get the face information for the subsampled object mesh.

Thanks for your time :)

**Comment by zc-alexfan** [comment]
sorry for the wait. CVPR craziness. :)

There is no face information here. The subsampled vertices here are sampled from the original mesh using [farthest-point-sampling](https://github.com/ziruiw-dev/farthest-point-sampling), so they are basically point clouds. 

However, the sub mesh vertices should be in the space of the object model in the canonical space (see the obj files in the object mesh folders), so I guess you can decimate the original obj mesh and use the same way defined in `object_tensors.py` to pose this new object model with faces.

Let me know if it is unclear.

**Comment by zc-alexfan** [comment]
@Eric-Gty have you found a solution to the Hasson layer conversion?

**Comment by Eric-Gty** [comment]
> @Eric-Gty have you found a solution to the Hasson layer conversion?

Hi Alex, sorry for the late reply. I'm still working on the conversion and will reach out to you when solve it. Btw, if you have any suggestions on this, I would be happy to take them :))

**Comment by zc-alexfan** [comment]
Let me ask around.
