### ISSUE TITLE
Can't download data.

### ISSUE THREAD

**Issue by Arthur151** [zc-alexfan/arctic#17]
@zc-alexfan 
Thanks for making such a great dataset. 
I am a student from China. I have tried your script for downloading data but failed. The login part is passed but the downloading process was stucked at the beginning. I have tried many VPN to switch to oversea network but still didn't work. Could you please check the download link?
Best,
Yu

**Comment by zc-alexfan** [comment]
Hi Arthur, it works on my side. I think you can check the download speed and see if it is just slow to download. On my end, it was downloading at 150kb/s, which is a lot slower than usual. It is possible that many people are downloading the dataset right now. 

I have push a new commit which allows you to download smaller files first in the dry-run. So try to pull the updates and run the dry run again. This allows you to test if smaller files can be downloaded. Thus, you can rule out VPN issue.

**Comment by Arthur151** [comment]
@zc-alexfan ，
Thanks, Doc. Zicong,

It can download while extremely slow. Thanks for your quick response. 

Best,
Yu

**Comment by zc-alexfan** [comment]
The server seems to be less busy; it is full speed for me now. Maybe you can try again.
