### ISSUE TITLE
Hand joint ordering

### ISSUE THREAD

**Issue by anjugopinath** [zc-alexfan/arctic#18]
Hi,

Does arctic follow the same joint ordering as the below figure:
<img width="122" alt="image" src="https://github.com/zc-alexfan/arctic/assets/4654298/e4b6722b-f575-4972-934f-de31f4d1e97c">

Could you tell me where I can find the information on the joint ordering for both the left and right hands, please?

Thank You.

**Comment by zc-alexfan** [comment]
Updated docs for joint convention (https://github.com/zc-alexfan/arctic/blob/master/docs/data/data_doc.md).
