### ISSUE TITLE
Evaluating the predicted weak perspective camera

### ISSUE THREAD

**Issue by ap229997** [zc-alexfan/arctic#20]
The predicted weak perspective camera is converted into the translation term, which is then used to compute the vertices and joints in camera coordinate frame. However, during evaluation, all the 3D locations are shifted to the wrist joint and then metrics are computed. This effectively gets rid of any translation error. Is there any reason why the metrics are not computed in the camera frame?

**Comment by zc-alexfan** [comment]
Which metric you refer to?

**Comment by ap229997** [comment]
I was mainly looking at `mpjpe_ra` but the same is the case for other metrics as well. I understand that global translation does not matter much for contact and interaction metrics.

**Comment by zc-alexfan** [comment]
Yes, the global translation does not matter. Also, MPJPE_RA is also root-relative.
