### ISSUE TITLE
gt_transl in process_data in process_arctic.py

### ISSUE THREAD

**Issue by ap229997** [zc-alexfan/arctic#23]
Shouldn't [gt_transl](https://github.com/zc-alexfan/arctic/blob/0847170d4ccd52313690d890f507b717c7c32116/src/callbacks/process/process_arctic.py#L79) and [T0](https://github.com/zc-alexfan/arctic/blob/0847170d4ccd52313690d890f507b717c7c32116/src/callbacks/process/process_arctic.py#L39) be the same?

If the global orientation of both the object and hand are with respect to camera coord space, then the object cano space and MANO cano space are different than the camera coord space by only a translation component.

Also, shouldn't `targets["mano.j3d.full.r"]` and `targets["mano.j3d.cam.r"]` be the same since both are in camera coord space?

**Comment by zc-alexfan** [comment]
`targets["mano.j3d.full.r"]` is the MANO joints in the original image coordinate (full resolution image). `targets["mano.j3d.cam.r"]` is in the coordinate of cropped image with the bounding box.
