### ISSUE TITLE
Joint visibility labeling

### ISSUE THREAD

**Issue by chae0382** [zc-alexfan/arctic#26]
I want to label joint visibility. In a previous response, it was mentioned to use segmentation masks, so I'm currently modifying the 'python scripts_data/visualizer.py --object --smplx --headless' script. During this process, I'm facing difficulty in obtaining segmentation mask images that match the cropped images. Can I get some advice on this part?

**Comment by zc-alexfan** [comment]
Hi, I am travelling right now. But a quick reference, you can see how the cropped image is related to the original one based on this function [here](https://github.com/zc-alexfan/arctic/blob/296bc1d9ae4a916710ab46ef3bfd4729e5217d01/src/datasets/arctic_dataset.py#L103C13-L103C26). When `speedup=False`, it refers to the original images.

**Comment by chae0382** [comment]
It was helpful. Thank you for the quick response.
