### ISSUE TITLE
NameError: name 'to_homo_batch' is not defined

### ISSUE THREAD

**Issue by kelvin34501** [zc-alexfan/arctic#3]
Exception thrown when running the following command:
```bash
python -m scripts_data.process_seqs --mano_p ./data/arctic_data/data/raw_seqs/s01/capsulemachine_use_01.mano.npy --export_verts
```

I am on commit ```20f5b6b464328621bf167b882f43ec14b127e7b4```

More details later...

**Comment by zc-alexfan** [comment]
I added the missed functions in transform.py. You can pull the repo. Let me know if anything else is missing.
