### ISSUE TITLE
Updated intrinsics for the cropped images? 

### ISSUE THREAD

**Issue by coreqode** [zc-alexfan/arctic#31]
Hey!
Thanks for this amazing work. I wanted to use the pre-cropped images however I can't find the modified intrinsics after the cropping? Is there a way to recover it? 

Thanks.

**Comment by AG-108** [comment]
I have the same question, do you happen to find the updated parameters? I'm especially confused about the cropping of the exocentric cam images.

**Comment by zc-alexfan** [comment]
@AG-108 

See FAQ for an explanation (https://github.com/zc-alexfan/arctic/blob/master/docs/faq.md). Hope it helps.
