### ISSUE TITLE
Marker positions in 3D or 2D

### ISSUE THREAD

**Issue by heydarshahi** [zc-alexfan/arctic#32]
Dear all,

Thanks for this amazing dataset. I have been working on it and need to find out the positions of the markers, either in 3D (world coordinate) or 2D (image coordinate). I looked through the data documentation and found 5 ego-centric camera marker positions, but not the other markers, e.g., the ones on the hands.

Exploring the code in [`src/utils/eval_modules.py`](https://github.com/zc-alexfan/arctic/blob/9a4269730345c54232eec96756818af43360cfa4/src/utils/eval_modules.py#L262C10-L262C10), I found the `joints_gt` variable being used with the dimensions `Nx14x3` which I can guess is for the 3D marker positions. If my guess is correct, it means that these marker positions can be extracted using `scripts_method/evaluate_metrics.py` which uses the models.

My question is: is there another way I can extract the marker positions without the need to run the models?

Many thanks in advance!
Amin

**Comment by zc-alexfan** [comment]
Hi Amin, thanks for your interest. 

I will work on releasing the mocap data this month. I will let you know in this issue once it is ready.

Alex

**Comment by heydarshahi** [comment]
Thanks, Alex! Looking forward to the release of the marker data.

In the meantime, I wonder if the `joints_gt`variable used in [`eval_modules`](https://github.com/zc-alexfan/arctic/issues/32#:~:text=src/utils/eval_modules.py) is actually coming from the marker positions? 

If that's the case, looking through the code, it seems to me that ground-truths are being computed, but not stored. Is that correct? 

If that's _also_ the case, is this data coming from `splits`? Or is it coming from the [leaderboard data](https://github.com/zc-alexfan/arctic/blob/master/docs/leaderboard.md#submitting-to-leaderboard)?

**Comment by zc-alexfan** [comment]
`joints_gt` is the ground-truth 3D keypoint of the MANO hand. So it is not directly related to the marker positions. However, MANO was registered to the markers during MoSH++.

**Comment by zc-alexfan** [comment]
@heydarshahi 

MoCap can be downloaded and visualized now. See changes in this [commit](https://github.com/zc-alexfan/arctic/commit/b4de88e758e3a70c72650b0345371d774169bff0).

**Comment by heydarshahi** [comment]
That's amazing, thanks!

**Comment by zc-alexfan** [comment]
Yes it is in mm (https://github.com/zc-alexfan/arctic/blob/master/docs/data/data_doc.md) as mentioned in the docs.

The mocap data is the raw data, which was in mm and then in my postprocessing I used meter.
