### ISSUE TITLE
Hand-Object Tracking

### ISSUE THREAD

**Issue by samueleruffino99** [zc-alexfan/arctic#33]
Are you planning to setup a pipeline for Object tracking task?
Moreover, do you think ARCTIC would be a good benchmark for object tracking (using hand motion prior in some way)?
If so, how could I get 2D objects' bounding boxes extracting from the poses?
Thank you and great work!

**Comment by zc-alexfan** [comment]
Hi, we don't have plan to create an object tracking task from hand motion. But I had a few ideas on object pose estimation from hand pose. I think you can still learn a method to track object poses from hand poses for ARCTIC objects. 

Could you clarify what you meant by "object 2D bounding box"?

**Comment by samueleruffino99** [comment]
Maybe I will try to improve the object pose attending some information on hand poses (both left and right) and vice-versa.
With "object 2D boxes" I am meaning the 2D projections of object onto the image plane.

**Comment by samueleruffino99** [comment]
Hello,

I am doing a Master Thesis at ETHZ, and maybe I could ask my supervisor to collaborate, if you want.
I am currently working on object tracking task (trying to improve it by fusing hand motion prior in some way), but it seems very challenging and pointless at this time.
I think estimating the object pose from hand pose would be much more motivating and reasonable.

Let me know what you think, and thank you !

Best regards,
Samuele Ruffino

**Comment by zc-alexfan** [comment]
I see. The preprocessing code already projected 3d vertices of the object to 2d before defining the 2d bounding boxes (see [here](https://github.com/zc-alexfan/arctic/blob/e54eaf2329177e2bef427841c02dde25d0cabf29/src/arctic/processing.py#L57). 

So I suggest to check out our preprocessing script [here](https://github.com/zc-alexfan/arctic/blob/master/scripts_data/process_seqs.py). See [here](https://github.com/zc-alexfan/arctic/blob/master/docs/data/processing.md) for information on how to run it.
