### ISSUE TITLE
Is there a way to generation full body motion together with the Arctic hand motions?

### ISSUE THREAD

**Issue by z050209** [zc-alexfan/arctic#34]
If we want to use the ARCTIC dataset like GRAB for full body hand object interaction, is there any method to recover the full body motion for ARCTIC? Thanks.

**Comment by zc-alexfan** [comment]
Our documentation states the SMPLX annotation is included. See: https://github.com/zc-alexfan/arctic/blob/master/docs/data/data_doc.md
