### ISSUE TITLE
Problem regarding translation

### ISSUE THREAD

**Issue by JubSteven** [zc-alexfan/arctic#35]
Thank you for your great work! I want to ask about the translation of the hand and the object. I want to get the object verts for a given frame, so I first fetched the vertices from the mesh file, and then try to apply the appropriate transform. The rotations seems correct using `obj_rot_cam`, but there seemed to be some issue with `obj_trans`, as shown in the following figure of reprojection result (using the intrinsics). I wonder if I should apply some other transformation on the translation, or should I multiply a scalar to it? Thanks.

![image](https://github.com/zc-alexfan/arctic/assets/95260261/e672496f-e7c8-4dbb-b9c7-6e1606c10f1c)

**Comment by zc-alexfan** [comment]
Hi, did you use my starter code or you did something differently? Also, it seems like your rotation is also incorrect?

**Comment by JubSteven** [comment]
I am trying to write a dataloader to best suit my current task. I have used `obj_rot_cam`  and `obj_trans` from the annotations, and roughly did something like this, where `obj_verts_can` are verts loaded from the object mesh. Then I reproject the `verts_3d` to 2d by intrinsics to validate whether the transformation is correct.
```python
def get_obj_transf(self, idx):
    sample = self.load_sample(idx)
    R = aa_to_rotmat(sample["obj_rot_cam"])[sample["cam_id"]]
    t = sample["obj_trans"]
    transf = build_SE3_from_Rt(R, t)
    return transf

def get_obj_verts_3d(self, idx):
    verts_c = self.get_obj_verts_can(idx)
    obj_transf = self.get_obj_transf(idx)
    verts_3d = SE3_transform(verts_c, obj_transf)
    return verts_3d
```

**Comment by zc-alexfan** [comment]
Did you transform to the world first and then do world2cam transform? Because if I remember correctly, the 6DoF object pose is wrt. the world. Then you can use individual extrinsics to map to the camera. 

This shows examples on how to map to world and then to camera: https://github.com/zc-alexfan/arctic/blob/914898144429515bf86b6c91c155f00b63542304/src/arctic/processing.py#L80

**Comment by JubSteven** [comment]
Thanks, I will check it out.

**Comment by JubSteven** [comment]
After a while I have figured out the right solution to this problem, and I have put up the code as follows. It's worth noting that the translation in `cam_extr` is in `m` while `obj_trans` is in `mm`. I have set the translation to `mm` and it works fine (omitted in `self.get_cam_extr`)

```python
def get_obj_transf(self, idx):
    sample = self.load_sample(idx)
    R = aa_to_rotmat(sample["obj_rot"])
    t = sample["obj_trans"]
    T1 = build_SE3_from_Rt(R, t)
    T2 = self.get_cam_extr(idx)
    transf = T2 @ T1
    return transf
```
