### ISSUE TITLE
SMPLX shape

### ISSUE THREAD

**Issue by troxlepa** [zc-alexfan/arctic#37]
Thanks for this great dataset!

I was looking at the data format docs for SMPLX [here](https://github.com/zc-alexfan/arctic/blob/master/docs/data/data_doc.md) and noticed that there is no shape parameter included in the *.smplx.npy files.
To my understanding, the shape is required to reconstruct the joints/verts.

Am I missing something?

**Comment by zc-alexfan** [comment]
Hi,

Shape parameters do not capture fine-grained details on the body. Therefore, we directly obtain the body template from body scan (https://github.com/zc-alexfan/arctic/blob/914898144429515bf86b6c91c155f00b63542304/common/body_models.py#L109). 

The vtemplate is the personalized template for the person in the canonical space. Then it is regressed to joints. 

If you want to use shape parameters while allowing the loss of details, you can fit SMPLX vertex-to-vertex to the vtemplate. 

Hope it clarifies.
