### ISSUE TITLE
Does MANO parameters equal to SMPLX hand parameters?

### ISSUE THREAD

**Issue by phj128** [zc-alexfan/arctic#40]
Hi, I have a question about MANO parameters and SMPLX parameters.

The MANO right hand parameters at frame 0 (box_use_01.mano.npy) is:
array([-0.03240527,  0.27357996, -0.44066623, -0.15148902, -0.19981687,
       -0.6955209 ,  6.558325  , -0.38321212,  0.8501508 ,  0.45173895,
        0.18395485, -0.39749008,  0.06304266, -0.11010664, -0.6733147 ,
        5.1536746 ,  0.26592368,  2.5213878 ,  0.4855672 , -0.2268661 ,
        0.24746093,  0.26659805, -0.05636495, -0.563865  ,  3.304417  ,
        0.31140158,  4.6122    ,  0.30845642, -0.16647121, -0.4377692 ,
        0.24876864, -0.02071797, -0.6238626 ,  5.9167466 ,  0.02213376,
        1.8504663 , -0.9403614 ,  0.6202517 , -0.63148606, -0.0362047 ,
       -0.23572953,  0.97068465, -0.40886796,  0.5357393 , -1.2295284 ],
      dtype=float32)

While SMPLX right hand pose at frame 0 (box_use_01.smplx.npy) is:
array([ 0.0094533 ,  0.16874607, -0.08016084, -0.05645293, -0.02849651,
        0.07896784,  0.1604375 , -0.05796457,  0.13873944,  0.1402729 ,
        0.07300756,  0.09562486, -0.11038493, -0.06354734,  0.1671049 ,
       -0.03375542,  0.00310679, -0.29383537, -0.13252321, -0.0102099 ,
        0.6954388 ,  0.17532377,  0.09140654,  0.19590265, -0.40491733,
       -0.15230231, -0.5940853 ,  0.05956102, -0.04324804,  0.25968423,
       -0.08441725, -0.03401042,  0.04836456, -0.06257863,  0.06051512,
       -0.14253886, -0.13492593,  0.1548856 , -0.38249287, -0.41815382,
        0.07842843,  0.58350015, -0.06046534,  0.25589123, -0.72547275],
      dtype=float32)

It seems that they are not equal.  I thought they described the same hand pose, what are the differences between them?

**Comment by zc-alexfan** [comment]
To my knowledge they are not the same hand pose space.

**Comment by phj128** [comment]
Thanks.
