### ISSUE TITLE
Cropped image size && mask image size

### ISSUE THREAD

**Issue by liushawn618** [zc-alexfan/arctic#43]
Dear team, thanks for your great work! When I visualize mask images, I find that the mask image size is 1600 * 900, but the cropped image size is 1000 * 1000, so the mask images can't match the cropped images pixel by pixel. How can they be exactly matched? I'd be really appreciated if you could give me some advice.

**Comment by zc-alexfan** [comment]
Hi @liushawn618, which mask images do you refer to?

**Comment by liushawn618** [comment]
mask images of gt_mesh
