### ISSUE TITLE
Hand-object mesh mismatch with the manopth

### ISSUE THREAD

**Issue by GuanHY** [zc-alexfan/arctic#44]
Hi Alex,

I just tried to use the differentiable manolayer here: https://github.com/hassony2/manopth/blob/master/manopth/manolayer.py, to reproduce the hand-object  mesh with the provided beta and theta parameters in arctic_data/data/raw_seqs(https://github.com/zc-alexfan/arctic/blob/master/docs/data/README.md). But I find that the visualization results are always abnormal, such as fingers.
![7d0f5d2eeb63c8ab956cc64e91d554c](https://github.com/zc-alexfan/arctic/assets/53296096/550d1085-0909-4172-ace0-c4fe8d5b3924)
![ff6f31479eaac3bb2916459016a60bc](https://github.com/zc-alexfan/arctic/assets/53296096/8b8b97a5-40aa-433e-8747-92f275372fb1)
![54daf3035c5e5ba3ff69006693e204f](https://github.com/zc-alexfan/arctic/assets/53296096/7bafd94c-2e91-47db-a45a-2ee26d25f4eb)
![e906e293c0cdf9d85df5bf7846d5550](https://github.com/zc-alexfan/arctic/assets/53296096/d77d4890-a8bf-455d-b512-24476b8df20c)

I've noticed that you use AITviewer for visualization. I'd like to ask if there are any notable differences worth paying attention to?Do you have any guess on the cause for this, or have you tried to use their manolayer before?

**Comment by zc-alexfan** [comment]
Sorry, we mainly tested out with smplx mano model. There was an issue raised a year ago which seems to show similar issues but I  have not used the mano layer from hasson before.

**Comment by GuanHY** [comment]
Yes, I've also read that issue and it appears that it was not resolved in the end. 
Thank you very much for your response. I will look into the SMPLX mano model to see if it can help address the issue we're facing
