### ISSUE TITLE
material in top.obj and bottom.obj

### ISSUE THREAD

**Issue by MandiZhao** [zc-alexfan/arctic#49]
Not sure if this is expected -- the part-level mesh .obj files refer to a "material_0.mtl" which doesn't seem to exist in my downloaded data. 
I manually changed that line to "material.mtl" in top.obj and bottom.obj for each object and the texture looks good, e.g.
<img width="501" alt="Screenshot 2024-08-14 at 9 42 18 AM" src="https://github.com/user-attachments/assets/d8e1ddf8-a3c4-4091-a4f8-850bf54fb700">

**Comment by zc-alexfan** [comment]
Hi @MandiZhao, Yes, that's correct. I think the material file that did not exist is from the original scan. You may ignore it.
