### ISSUE TITLE
Some questions about training

### ISSUE THREAD

**Issue by JoyboyWang** [zc-alexfan/arctic#5]
Thanks for your great job! 

I have downloaded the codes and data using the same splits as your baselines following the instructions. Everything works fine until I start training the **ArcticNet-SF** from scratch, and my issues are as follows:

1. During the training process, I found that there are several warnings telling me that it was unable to load the images, which I found did not exist or were corrupted. I have downloaded the dataset twice on different computers, and the problem still exists. And here is the snapshot:
<img width="1162" alt="image" src="https://github.com/zc-alexfan/arctic/assets/22212974/da03fb56-2a81-41ab-8359-b83b39383df8">
I compared the generated checksum.json with the provided one and found that the only difference is that all the paths with the prefix "/data/images_zips" are missing, but I think this is because I downloaded the cropped version instead of the full-resolution one.

2. In your default configuration, you use a batch size of 64. However, I found that it would take a very long time (e.g. 7~8 hours per epoch) for training on a single RTX 3090.  Is that normal? 

3. So here comes the third question. In your paper, I didn't find any descriptions of the training time and the hardware you use for the baselines. Could you please clarify it?

Thanks in advance!

**Comment by JoyboyWang** [comment]
Got it. Thanks a lot. But I still have one question: 

Is the released configuration (e.g. batch_size=64 and #epochs=20 for allocentric ArcticNet-SF) the recommended one? Since 64 is relatively small compared to the GPU memory of A100, have you tried a larger batch size?

**Comment by zc-alexfan** [comment]
I have not turned the batch size as the training speed is bounded by IO not gpu utils for me.

**Comment by JoyboyWang** [comment]
Okay, thanks very much!
