### ISSUE TITLE
MANO shape parameter of the left hand

### ISSUE THREAD

**Issue by mks0601** [zc-alexfan/arctic#50]
Hi Alex, how are you doing?
Thanks for your great dataset.
It seems there is a problem in the MANO shape parameter of the left hand.

![s01_box_grab_01_0_70_left_zero](https://github.com/user-attachments/assets/9161c953-6e44-4d41-b938-dfcf58e6b61c)
The above is from left hand of s01 / box_grab_01 / 0 / 70.
I set all inputs to zero except the shape parameter, where MANO layer is initialized with flat_hand_mean=True for the visualization.
As you can see, although flat_hand_mean=True, finger is bent, which is caused by some weird MANO shape parameter.
This makes artifacts when posed like the below image.

![s01_box_grab_01_0_70_left](https://github.com/user-attachments/assets/68163f1a-c31b-4f3d-be1b-bb52322c026c)
This is from the same frame, but I passed all inputs to MANO layer including hand_pose.
As you can see, bent index finger becomes weird when posed.

I found that there is no problem for the right hand. Could you let me know why this happens?
BTW, do you know there is a bug in the shapedirs of the MANO left hand?
You can see the bug in here: https://github.com/vchoutas/smplx/issues/48
Simply saying, when we pass the same shape parameter to the left/right MANO layer, output geometry looks very different.
We need to do `mano_layer['left'].shapedirs[:,0,:] *= -1` fo fix this bug.
FYI, although I do `mano_layer['left'].shapedirs[:,0,:] *= -1`, I can't remove the bug. All the above figures are from MANO layer as it is without doing `mano_layer['left'].shapedirs[:,0,:] *= -1`.

**Comment by zc-alexfan** [comment]
Hi Gyeongsik, 

Thanks for reaching out! Yes, recently, I also realized there was a bug in MANO left hand shape space. Given CVPR deadline, I cannot rerun mosh to correct this. However, maybe you can fit MANO to the SMPLX mesh? Hope this will address the issue.

**Comment by mks0601** [comment]
Awesome. Thanks for checking. See you at ECCV :)
