### ISSUE TITLE
projected SMPL-X meshes don't overlay well in allocentric views

### ISSUE THREAD

**Issue by nehc0** [zc-alexfan/arctic#52]
Hello. I use my custom visualization pipeline  for allocentric views, transforming the SMPL-X mesh vertices from world coordinates to pixel assuming a pinhole camera model using the extrinsic and intrinsic matrices you provide in `meta/misc.json`. However, I observe that in some cases the projected meshes don't overlay well with the humans in images. Is it my problem?

Some examples:

[s01/box_use_02/6]
![s01/box_use_02/6](https://github.com/user-attachments/assets/ee3bc387-6ddf-4388-a00f-500d5007fe98)

[s01/espressomachine_grab_01/7]
![s01/espressomachine_grab_01/7](https://github.com/user-attachments/assets/0575bc7c-9536-4a02-be06-e08502c9a9ae)

[s08/capsulemachine_use_01/5]
![s08/capsulemachine_use_01/5](https://github.com/user-attachments/assets/ae815547-6780-4eda-b29c-b216e358be02)

**Comment by zc-alexfan** [comment]
Thanks for your question. Maybe you can test with my visualization because I also cannot see the issue here.

**Comment by nehc0** [comment]
> Thanks for your question. Maybe you can test with my visualization because I also cannot see the issue here.

Did you crop image or apply distortion before visualization for allocentric views?

**Comment by zc-alexfan** [comment]
Distortion is not a main factor in allocentric view. My visualization script first loads the data and then apply the visualization. Maybe you can just try that data loader.

**Comment by nehc0** [comment]
> Distortion is not a main factor in allocentric view. My visualization script first loads the data and then apply the visualization. Maybe you can just try that data loader.

Solved. I made a stupid mistake of using 'neutral' rather than gendered smplx for all meshes. After I fixed it, the rendered results seemed much more acceptable:

[s01/box_use_02/6-fix]
![s01-box_use_02-6_fix](https://github.com/user-attachments/assets/8f7ac132-49f6-40bb-bd9a-5eb383388802)

[s01/espressomachine_grab_01/7-fix]
![s01-espressomachine_grab_01-7_fix](https://github.com/user-attachments/assets/54c0f691-4906-4616-8a19-a75bce01be64)
