### ISSUE TITLE
What difficulties might arise when transferring existing methods for single-hand and object joint reconstruction to joint reconstruction of two hands and an object?

### ISSUE THREAD

**Issue by liushawn618** [zc-alexfan/arctic#53]
What difficulties might arise when transferring existing methods for single-hand and object joint reconstruction to joint reconstruction of two hands and an object?

**Comment by zc-alexfan** [comment]
In two hand setting, the contact is not always in one hand. Your model needs to reason hand-object contact for the correct hand (see CDev in our paper). Also depth ambiguity (see MRRPE). 

See our new paper: https://arxiv.org/abs/2403.16428
