### ISSUE TITLE
Depth GT?

### ISSUE THREAD

**Issue by ViccccciV** [zc-alexfan/arctic#55]
Great work!

I am wondering if the datasets provide Ground truth depth information for each frame?
Thank you!

**Comment by zc-alexfan** [comment]
you can render the dataset with our visualizer https://github.com/zc-alexfan/arctic/blob/master/docs/data/visualize.md

**Comment by ViccccciV** [comment]
Thank you for your prompt answer! But I find that I could only render the GT depth of object and hands, while the rest is used by a billboard. Do we also have the depth for the whole scene of the egocentric view?

**Comment by zc-alexfan** [comment]
Sorry, we only have the object and hands. The table and small box do not move in each sequence. So theoretically you can fit a plane to the object bottom when it is not picked up, which should be easy to do.

**Comment by ViccccciV** [comment]
Thank you for your prompt help!
