### ISSUE TITLE
Clarification in splits data

### ISSUE THREAD

**Issue by Hamzac070** [zc-alexfan/arctic#57]
Hey

Great work for developing such a comprehensive dataset. i have Two questions: -
1. The paper describes two kinds of actions, grasp and use. However, the data has use_01, use_02, use_03 and use_04 in some instances. Are these repeated trials of using a subject using the same object in a different way? Are there only 2 verbs in ARCTIC, grasp and use or more like grasp, use1, use2,...?
2. In the splits foler, p2_val.npy has {imgnames, data_dict} where imgnames for a particular sequences lets say s05/box_grab_01/0 has 657 image names whereas the corresponding data_dict['s05/box_grab_01/0']['cam_coord']['joinmts.right'] is of the shape (677, 10, 21, 3) and the image folder also has 677 images, so why this mismatch?

Thanks in advance.

**Comment by zc-alexfan** [comment]
Hi, 

1. Yes, we have two types of motions and the numbers are different motions of the same type. We didn't constrain the subject's interaction so they can have very different motion for the same type. 
2. The first several frames from images are typically black in the raw data, so I remove the first and the last 10 frames.
