### ISSUE TITLE
missing images?

### ISSUE THREAD

**Issue by noahcao** [zc-alexfan/arctic#8]
I found three images are missing in my downloaded dataset:

- cropped_images/s01/laptop_use_04/7/00737.jpg
- cropped_images/s01/espressomachine_grab_01/4/00443.jpg
- cropped_images/s08/mixer_use_02/3/00295.jpg

I wonder if that is missing in the dataset or maybe just some error occured during my downloading....

**Comment by zc-alexfan** [comment]
See issue #5

Basically, a few images are corrupted and it won't affect the score much because the loss function and metric will ignore missed images.

Will update the corrupted ones later.

**Comment by noahcao** [comment]
Thanks for the timely reply! 

Really good work and I am impressed by the comprehensive tutorial documents. Looking forward to the release of v1.0
